services:
  postgree:
    image: postgres:latest
    container_name: postgreeServer
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Pg@123
      POSTGRES_USER: postgres
      POSTGRES_DB: todos
